[package]
name = "nyatidraw-project-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nyatidraw-api.workspace = true
nyatidraw-document.workspace = true
nyatidraw-editor.workspace = true
nyatidraw-project.workspace = true
nyatidraw-project-redb = { path = "../project-redb", default-features = false }
nyatidraw-tiles.workspace = true
nyatidraw-web-core.workspace = true

[dev-dependencies]
blake3.workspace = true

[lints]
workspace = true
