[package]
name = "nyatidraw-input-platform"
version.workspace = true
edition.workspace = true

[dependencies]
nyatidraw-input.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "=0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Pointer",
    "Win32_UI_WindowsAndMessaging",
] }

[lints]
workspace = true
