[package]
name = "nyatidraw-project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nyatidraw-api.workspace = true
nyatidraw-brush.workspace = true
nyatidraw-document.workspace = true
nyatidraw-history.workspace = true
nyatidraw-input.workspace = true
nyatidraw-stroke.workspace = true
nyatidraw-tiles.workspace = true
zstd = { version = "=0.14.0", default-features = false }

[lints]
workspace = true
